"""Initial Migration

Revision ID: 4971f98836a6
Revises: b0e432a83beb
Create Date: 2020-12-13 00:21:30.262992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4971f98836a6'
down_revision = 'b0e432a83beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_pic_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_pic_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
