"""Initial Migration

Revision ID: b0e432a83beb
Revises: 9044046e31be
Create Date: 2020-12-12 22:36:11.395293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e432a83beb'
down_revision = '9044046e31be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_pic_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'post_pic_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
